export const START_LOADING = 'START_LOADING'
export const STOP_LOADING = 'STOP_LOADING'
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR'
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_SINGLE_PRODUCT_ERROR = 'GET_SINGLE_PRODUCT_ERROR'
export const GET_SINGLE_PRODUCT = 'GET_SINGLE_PRODUCT'


//CART
export const ADD_TO_CART = 'ADD_TO_CART'